### PR TITLE
merge

### PR DESCRIPTION
**Pull request by octoturt**
i used push-notifications as a base even though i didn't implement them. god. i am not a developer

### CODE REVIEW

**Comment by octoturt** [comment]
ok nerd

**Comment by octoturt** [comment]
wait no

**Review by octoturt — COMMENTED** [review]
how did i get here

**Comment by octoturt** [comment]
wait i asked it to merge the wrong thing i am so sorry pwootage

**Comment by Pwootage** [comment]
Oh this is a cool idea. If you do fix it and open another merge; I'll definitely review & merge it :)

Slack is at last compiled for ARM; but I imagine safari may still be more power efficient for it

**Comment by octoturt** [comment]
Thanks! Slack does publish their app as a universal binary, however it is still Electron, which is less than ideal, and because WebKit has better power efficiency (especially on Intel, which my current Mac still is) I wanted to at least try to find out what difference it would make, as every drop of battery counts when you're trying to get work done and are away from an outlet!

I sincerely apologize for the nonsensical pull request, I'm a very unexperienced developer and had a lot of trouble with Xcode and Git at first. I'll definitely try to get it in a state I'm happy with and make a PR to put my changes into the original project! DiscordSafari was a lifesaver for me and I'd love to contribute to it.

**Pull request closed without merging**
